# First few lines copied from https://docs.github.com/en/actions/quickstart
name: GitHub Action for scanning the resulting Docker container image
run-name: ${{ github.actor }} is scanning the Docker container image that this project would build 🕵
on: [push]
jobs:
  Scan-Resulting-Docker-Image:
    runs-on: ubuntu-latest
    steps:
      # Steps below copied from https://github.com/marketplace/actions/anchore-container-scan
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: build local container
        uses: docker/build-push-action@v2
        with:
          tags: localbuild/testimage:latest
          push: false
          load: true

      - name: Scan image
        uses: anchore/scan-action@v3
        with:
          image: "localbuild/testimage:latest"

